AUX Relax git pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -25,12 +25,12 @@ echo "Checking files: $FILES"
 for i in $FILES; do
 	echo "$i"
 	perl -Ilib -Ilib/perl5 -wc "$i" || fail "$i" - "Syntax error"
-	perl -Mwarnings=FATAL,all -Mstrict -Ilib -Ilib/perl5 -w "$i" || fail "$i" - Strict 
 	perl -wne '/\s\n/ and exit 1' "$i" || fail "$i" - "Spaces at EOL"
 	perlcritic "$i" || fail "$i" - "Perl critic"
 
 	# The module part
 	echo "$i" | egrep -q 'pm$' || continue;
+	perl -Mwarnings=FATAL,all -Mstrict -Ilib -Ilib/perl5 -w "$i" || fail "$i" - Strict 
 done 
 
 check_fail
